import { Theme } from '@mui/material';
import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles<Theme>(() => ({
  otherNewsTitle: {
    color: '#fff !important',
    fontSize: '36px !important',
    fontWeight: '700 !important',
    lineHeight: '50px !important',
    paddingTop: '80px !important',
    marginBottom: '40px !important',
    textTransform: 'uppercase',
    fontFamily: 'Open Sans, sans-serif !important',
  },
  PaperCard: {
    display: 'flex !important',
    boxShadow:
      'rgba(9, 30, 66, 0.25) 0px 4px 8px -2px, rgba(9, 30, 66, 0.08) 0px 0px 0px 1px !important',
    borderRadius: '5px !important',
    height: '100% !important',
    padding: '24px !important',
    gap: '16px !important',
  },
  BoxCard: {
    width: '100% !important',
    margin: '0 !important',
    padding: '18px 24px 18px 16px !important',
  },
  newItemTitle: {
    color: '#183B56 !important',
    display: '-webkit-box !important',
    overflow: 'hidden !important',
    boxSizing: 'border-box',
    wordBreak: 'break-word',
    fontWeight: '700 !important',
    lineHeight: '33px !important',
    whiteSpace: 'pre-line',
    marginBottom: '10px !important',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: '2',
    fontFamily: 'Open Sans, sans-serif !important',
    '&:hover': {
      cursor: 'pointer',
      color: '#0055A7  !important',
    },
  },
  newItemDesc: {
    color: '#5A7184 !important',
    display: '-webkit-box !important',
    overflow: 'hidden !important',
    boxSizing: 'border-box',
    wordBreak: 'break-word',
    lineHeight: '32px !important',
    whiteSpace: 'pre-line',
    marginBottom: '14px !important',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: '4',
    fontSize: '18px !important',
    fontFamily: 'Open Sans, sans-serif !important',
    minHeight: '128px',
  },
  buttonLower: {
    color: '#0055A7  !important',
    fontSize: '16px  !important',
    fontWeight: '700  !important',
    lineHeight: '22px  !important',
    textTransform: 'initial',
    textDecoration: 'underline',
    fontFamily: 'Open Sans, sans-serif !important',
  },

  image1: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderRadius: '5px',
  },
  loadMoreBox: {
    display: 'flex !important',
    marginTop: '60px !important',
    alignItems: 'center !important',
    marginBottom: '19px !important',
    justifyContent: 'center !important',
  },
  loadMoreButton: {
    padding: '16px 64px !important',
    fontSize: '16px !important',
    background: '#0055A7 !important',
    fontWeight: '600 !important',
    lineHeight: '22px !important',
    borderRadius: '8px !important',
    color: '#fff !important',
    marginBottom: '10px!important',
  },
}));
